name: Docker build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile: [tools]
    steps:
      - uses: actions/checkout@v2
      - uses: qlik-oss/ci-tools/action-print-event-info@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v2
      #   with:

      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     registry: ghcr.io
      #     repository: ilirb/${{ matrix.dockerfile }}
      #     tag_with_ref: true
      #     context: ${{ matrix.dockerfile }}/
      - name: Build Docker image
        # working-directory: "${{ matrix.dockerfile }}"
        uses: docker/build-push-action@v2
        with:
          context: "${{ matrix.dockerfile }}/"
          tags: ghcr.io/${{ github.actor }}/${{ matrix.dockerfile }}:latest
          push: true
